version: "3.8"

services:
  broker:
    container_name: "eclipse-mosquitto"
    image: eclipse-mosquitto:latest
    # environment:
    #   - RABBITMQ_DEFAULT_USER=admin
    #   - RABBITMQ_DEFAULT_PASS=admin
    ports:
      # AMQP protocol port
      - '1883:1883'
      # HTTP management UI
      - '9001:9001'
